railsapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resource :users, :only => [:show]
  get 'users/:id' => 'users#show', :as => :user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  #root "devise/registrations#edit"
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]
end

railsapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

railsapp/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

railsapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name:  'Relationship',
           foreign_key: 'follower_id',
           dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name:  'Relationship',
           foreign_key: 'followed_id',
           dependent:   :destroy


  has_many :followers, through: :passive_relationships, source: :follower

  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  # validates :name, presence: true # Make sure the owner's name is present.

  def full_name
    self.name + ' ' + self.last_name
  end

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

railsapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def after_sign_in_path_for(resource)
        #edit_user_registration_path
        user_path(resource)
    end

    protected
    def configure_permitted_parameters
        #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :last_name, :description, :age, :date_of_birth, :country, :job) }
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name, :description, :age, :date_of_birth, :country, :job, :attachment])
    end
end

railsapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @users = User.first(5)
    end
end

railsapp/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

railsapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @title = "Users"
        @user = current_user
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def following
        @title = 'Following'
        @user  = User.find(params[:id])
        @users = @user.following
        render 'show_follow'
    end

    def followers
        @title = 'Followers'
        @user  = User.find(params[:id])
        @users = @user.followers
        render 'show_follow'
    end
end

railsapp/app/helpers/application_helper.rb
module ApplicationHelper
end

railsapp/app/helpers/home_helper.rb
module HomeHelper
end

railsapp/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

railsapp/app/helpers/users_helper.rb
module UsersHelper
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
end

railsapp/app/views/home/index.html.erb
<section class="info-section py-3 py-md-5">
  <div class="container">
  <div class="row">
    <div class="col-12 col-lg-6 pt-3 mb-5 mb-lg-0">
      <h1 class="site-headline">
      Create your profile and build your CV like a pro
      </h1>
      <div class="site-tagline mb-4">
      Designed for entrepreneurial software developers, SmProfiles is the place where you can search people mini CV's 
      </div>
      <div class="site-buttons mb-lg-3">
        <%= link_to "Explore Users", users_path, :class => 'btn btn-danger' %>
        <a class="btn btn-dark" href="#">View Docs</a>
      </div>
    </div>

    <div class="col-12 col-lg-6 pt-3 mb-5 mb-lg-0">
      <%= image_tag("coder.svg", :class => "home-img") %>
    </div>
  </div>  
  </div>
</section>

railsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smprofiles</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <div class="branding">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href=<%= root_path %>>
          <%= image_tag("RubyIcon.png", :class => "logo-icon mr-2") %>
          <span class="bold-logo-text">Sm<span class="logo-text">profiles</span>
          </span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-lg-auto">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                  <%= link_to 'Show profile', edit_user_registration_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-danger text-white" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <main>
   <%= yield %>
  </main>
</body>
</html>

railsapp/app/views/relationships/create.js.erb
document.querySelector("#follow_form").innerHTML = "<%= escape_javascript(render('users/unfollow')) %>"
document.querySelector("#followers").innerHTML = '<%= @user.followers.count %>'

railsapp/app/views/relationships/destroy.js.erb
document.querySelector("#follow_form").innerHTML = "<%= escape_javascript(render('users/follow')) %>"
document.querySelector("#followers").innerHTML = '<%= @user.followers.count %>'

railsapp/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div>
  <a href="<%= following_user_path(@user) %>" class="text-success">
    <strong id="following">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>" class="text-danger">
    <strong id="followers">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

railsapp/app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

railsapp/app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

railsapp/app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

railsapp/app/views/users/_user.html.erb
<div class="card" style="width: 18rem;">
  <% if user.attachment_url %>
    <img src="<%= user.attachment_url %>" class='card-img-top user-img' alt="">
  <% else %>
    <%= image_tag("default-men.png", :class => "card-img-top user-img") %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= user.name %> </h5>
    <p class="card-text"> <%= user.description.split(".")[0] if user.description %></p>
    <%= link_to 'View Profile', user, class: 'btn btn-info' %>
  </div>
</div>

railsapp/app/views/users/_users.html.erb
<div class="users-section">
  <h3><%= @title %></h3>
  <div class="user-container">
    <div class="card-deck">
      <% @users.each do |user| %>
        <%= render user unless user.name.blank? || user.description.blank? %>
      <% end %>
    </div>
  </div>
</div>

railsapp/app/views/users/index.html.erb
<%= render 'users' %>

railsapp/app/views/users/show.html.erb
<div>
<h3>User Info</h3>
<%= @user.name %>
<%= @user.last_name %>
<%= @user.email %>
<%= @user.description %>
<%= @user.age %>
<%= @user.date_of_birth %>
<%= @user.country %>
<%= @user.job %>
</div>

<h3>Cancel my account</h3>

<%= link_to "Back", :back %>

railsapp/app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-12">
    <%= render 'users' %>
  </aside>
</div>