phoenixapp/lib/phoenixapp_web/router.ex
defmodule PhoenixappWeb.Router do
  use PhoenixappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixappWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", PhoenixappWeb do
    pipe_through [:browser]#, PhoenixappWeb.Plugs.Guest] # Para restringir acceso
                                                        # Pero daña la navegación

    resources "/register", UserController, only: [:create, :new]
    #resources "/register", User
    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  scope "/", PhoenixappWeb do
    pipe_through [:browser]#, PhoenixappWeb.Plugs.Auth] # Para restringir acceso
                                                        # Pero daña la navegación

    delete "/logout", SessionController, :delete
    resources "/users", UserController, only: [:index, :edit, :show, :update, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixappWeb do
  #   pipe_through :api
  # end
end

phoenixapp/lib/phoenixapp_web/views/layout_view.ex
defmodule PhoenixappWeb.LayoutView do
  use PhoenixappWeb, :view
end

phoenixapp/lib/phoenixapp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Phoenixapp · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <div class="branding">
        <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brand" href="#">
            <img src="<%= Routes.static_path(@conn, "/images/phoenixicon.png") %>" alt="Phoenix Framework Logo" class="logo-icon mr-2"/>
            <span class="bold-logo-text">Sm<span class="logo-text">profiles</span>
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-lg-auto">
              <li class="nav-item">
                <%= link "Home", to: Routes.page_path(@conn, :index), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <%= if signed_in?(@conn) do %>
                <li class="nav-item">
                  <%= link "Show profile", to: Routes.user_path(@conn, :show, @current_user), class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete, class: 'nav-link' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link "Login", to: Routes.session_path(@conn, :new), class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link "Sign up", to: Routes.user_path(@conn, :new), class: 'btn btn-primary text-white' %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <main>
        <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>